version: "3.8"
services:
  front:
#    image: "arkravchenko/kommersant_nuxt"
    image: "kom"
#    restart: always
    networks:
      - my_network
    ports:
      - 3333:3333
    healthcheck:
      test: curl -f http://0.0.0.0:3333/healthz || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
#    depends_on:
#      - redis
#      placement:
#        constraints: [ node.role == worker ]
#  redis:
#    image: redis:6.0.6
#    networks:
#      - my_network
#    ports:
#      - 6379:6379
#    command: [ sh, -c, "rm -f /data/dump.rdb && redis-server" ] # disable persistence
#    deploy:
#      mode: global
#      update_config:
#        delay: 10s
#        order: start-first
#  #      placement:
#  #        constraints: [ node.role == worker ]
networks:
  my_network:
    driver: overlay
#    driver: bridge



